name: Question
description: Ask about something here.
labels: [question, status: pending triage]
body:
  - type: textarea
    attributes:
      label: What is your question?
    validations:
      required: true